services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - logs:/logs

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"

volumes:
  logs: